spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
  jpa:
    show-sql: false

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    com.kista: INFO
