spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kistadb
    username: kista
    password: kista

  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
